# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eARth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eARth
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'ARCL'


  target 'eARthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eARthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
