# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yourFit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yourFit
  pod ‘Firebase/Core’
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FBAudienceNetwork'

  target 'yourFitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'yourFitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
