# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARcher
pod 'Each', '~> 1.2'
pod 'FBAudienceNetwork'

  target 'ARcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARcherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
